spring.application.name=proyectomdweb

#-- CONFIGURACION DE BD (IMPORTANTE N) --#
# Ruta explícita para que Spring Boot encuentre el contenedor
spring.docker.compose.file=proyectomdweb/compose.yaml
# Conexión a la base de datos MySQL en Docker (Puerto 3309)
spring.datasource.url=jdbc:mysql://localhost:3309/llamadb?useSSL=false&serverTimezone=UTC
spring.datasource.username=llama
spring.datasource.password=llamadb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#-- CONFIGURACIÓN JPA/HIBERNATE --#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect